[pytest]
pythonpath = .
markers =
    e2e: marks tests as end-to-end tests
    unit: marks tests as unit tests
    update_snapshots: marks tests as snapshot tests
addopts = -q --tb=line
filterwarnings =
    ignore:.*Conversion of an array with ndim > 0 to a scalar is deprecated.*:DeprecationWarning
