[pytest]
filterwarnings =
    ignore:.*_UnionGenericAlias.*:DeprecationWarning
    ignore:.*_UnionGenericAlias.*:DeprecationWarning:google.genai.types
    ignore:Inheritance class AiohttpClientSession from ClientSession is discouraged:DeprecationWarning:google.genai._api_client
    ignore:Conversion of an array with ndim > 0 to a scalar is deprecated:DeprecationWarning

markers =
    unit: small unit tests
    e2e: end-to-end tests
