target-version = "py314"

[lint]
select = ["E", "F", "W"]
ignore = [
    "E402", # module-import-not-at-top-of-file (required for path modifications)
    "E501", # line-too-long
    "E701", # multiple-statements-on-one-line-colon
    "E731", # lambda-assignment
    "E741", # ambiguous-variable-name
    "E712", # true-false-comparison
    "W291", # trailing-whitespace
    "W293", # blank-line-contains-whitespace
    "F841", # unused-variable
]

[lint.per-file-ignores]
# Notebook cells commonly consume variables created by earlier interactive cells.
"notebooks/*.ipynb" = ["F821"]
