# Singa Green #1B4429
# Singa Green rgb(49, 122, 73)
# Singa Yellow #F5D819
# Singa Dark Yellow rgb(255, 208, 0)
# Singa Grey #E8ECEA


[theme]
base="dark"
backgroundColor="white"
secondaryBackgroundColor="#E8ECEA"
textColor="#1B4429"
# secondaryTextColor="#1B4429"
baseRadius="full"
primaryColor="#1B4429"
# secondaryColor="#F5D819"



[theme.sidebar]
backgroundColor="#1B4429"
secondaryBackgroundColor="rgb(49, 122, 73)"
textColor="white"
# secondaryTextColor="#1B4429"
primaryColor="rgb(255, 208, 0)"
# secondaryColor="#F5D819"

[client]
toolbarMode = "minimal"

[ui]
hideTopBar = true